package emit.esy.es.fieldworker;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.Toast;

import com.firebase.client.Firebase;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by Emil Makovac on 14/03/2015.
 */
public class AddEditUserActivity extends Activity{

    EditText fName, lName, email, pass;
    Button save;
    CheckBox cb;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.adduser_layout);

        fName = (EditText) findViewById(R.id.user_fName);
        lName = (EditText) findViewById(R.id.user_lName);
        email = (EditText) findViewById(R.id.user_email);
        pass = (EditText) findViewById(R.id.user_pass);
        cb = (CheckBox) findViewById(R.id.user_isAdmin);
        save = (Button) findViewById(R.id.btn_saveUser);


        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                saveUserToFirebase(fName.getText().toString(),
                                    lName.getText().toString(),
                                    email.getText().toString(),
                                    pass.getText().toString(),
                                    cb.isChecked());
            }
        });
    }

    private void saveUserToFirebase(String fName, String lName, String email, String pass, boolean isAdmin) {

        if((fName.length() <= 0) || (lName.length() <= 0) || (email.length() <= 0) || (pass.length() <= 0)){
            Toast.makeText(this, "All fields are required", Toast.LENGTH_SHORT).show();
        } else {
            Firebase ref = new Firebase("https://fieldworker.firebaseio.com/");

            // Generate a reference to a new location and add some data using push()
            Firebase postRef = ref.child("usersMap");
            Firebase newPostRef = postRef.push();

            String admin;
            //check boolean and cast to string
            if(isAdmin){
                admin = "1";
            } else {
                admin = "0";
            }
            // Add some data to the new location
            Map<String, String> user = new HashMap<String, String>();
            user.put("fName", fName);
            user.put("lName", lName);
            user.put("mail", email);
            user.put("password", pass);
            user.put("isAdmin", admin);
            newPostRef.setValue(user);
            // Get the unique ID generated by push()
            String postId = newPostRef.getKey();
            Log.d("AddUserActivity", "New id: " + postId);
        }
    }

}
